export const projects = [
	{
		img: '/ProjectImages/masai_refresh.png',
		title: 'Masai Refresh',
		des: 'A Quiz app that tests your knowledge based on your preferred stack topic, and analyses results. A comprehensive report is presented at the end of each quiz.',
		demo: '',
		live: 'https://refresh.masai.tech/quiz_topics',
		gitHub: 'https://github.com/masai-oss/Masai_Refresh.git',
		technologies: ['React', 'Redux', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: '/ProjectImages/bookmyshow.png',
		title: 'Clone of BookMyShow',
		des: 'BookMyShow website is basically for entertainment purposes, In this app, a user can book movie tickets by choosing the different theatres and timings accordingly. The user also can see some events happening around them and can attend the events.',
		demo: '',
		live: 'https://bookmyshow-clone-masaischool.netlify.app/',
		gitHub: 'https://github.com/arshadalitalwar/bookmyshow.git',
		technologies: ['React', 'Redux', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: '/ProjectImages/todo.png',
		title: 'Todo App',
		des: 'A ToDo application made using React, Redux and a few libraries, wherein the user can add a new task, change the status, edit it, edit sub-task and delete it.',
		demo: '',
		live: 'https://him-todo.netlify.app/',
		gitHub: 'https://github.com/himrd95/todo.git',
		technologies: ['React', 'Redux', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: '/ProjectImages/medium.png',
		title: 'Clone of Medium',
		des: 'Clone of a blogging web application, Medium where a user can read the blogs written by others and show their response also, one can share their thoughts by posting a blog.',
		demo: '',
		live: 'https://medium-web.netlify.app/',
		gitHub: 'https://github.com/himrd95/Medium-Clone.git',
		technologies: ['React', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: '/ProjectImages/fitness.png',
		title: 'Clone of Fitness Blender',
		des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
		demo: '',
		live: 'https://anshusagar.github.io/FitnessBlender/',
		gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
		technologies: ['HTML', 'CSS', 'javaScript'],
	},
	{
		img: '/ProjectImages/mailchimp.png',
		title: 'Mailchimp Clone',
		des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
		demo: '',
		live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
		gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
		technologies: ['HTML', 'CSS', 'javaScript'],
	},
];
