export const projects = [
	{
		img: 'https://github.com/himrd95/portfolio/blob/main/public/ProjectImages/masai_refresh.png?raw=true',
		title: 'Masai Refresh',
		des: 'A Quiz app that tests your knowledge based on your preferred stack topic, and analyses results. A comprehensive report is presented at the end of each quiz.',
		demo: '',
		live: 'https://refresh.masai.tech/quiz_topics',
		gitHub: 'https://github.com/masai-oss/Masai_Refresh.git',
		technologies: ['React', 'Redux', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: 'https://github.com/arshadalitalwar/bookmyshow/blob/main/bookmyshow-app/public/website_images/home_page.JPG?raw=true',
		title: 'Clone of BookMyShow',
		des: 'BookMyShow website is basically for entertainment purposes, In this app, a user can book movie tickets by choosing the different theatres and timings accordingly. The user also can see some events happening around them and can attend the events.',
		demo: '',
		live: 'https://bookmyshow-clone-masaischool.netlify.app/',
		gitHub: 'https://github.com/arshadalitalwar/bookmyshow.git',
		technologies: ['React', 'Redux', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: 'https://github.com/himrd95/todo/blob/master/public/dashboard.png?raw=true',
		title: 'Todo App',
		des: 'A ToDo application made using React, Redux and a few libraries, wherein the user can add a new task, change the status, edit it, edit sub-task and delete it.',
		demo: '',
		live: 'https://him-todo.netlify.app/',
		gitHub: 'https://github.com/himrd95/todo.git',
		technologies: ['React', 'Redux', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: 'https://user-images.githubusercontent.com/73213873/107113597-f547e200-6885-11eb-8abd-72106074907a.png',
		title: 'Clone of Medium',
		des: 'Clone of a blogging web application, Medium where a user can read the blogs written by others and show their response also, one can share their thoughts by posting a blog.',
		demo: '',
		live: 'https://medium-web.netlify.app/',
		gitHub: 'https://github.com/himrd95/Medium-Clone.git',
		technologies: ['React', 'HTML', 'CSS', 'javaScript'],
	},
	{
		img: 'https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966',
		title: 'Clone of Fitness Blender',
		des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
		demo: '',
		live: 'https://anshusagar.github.io/FitnessBlender/',
		gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
		technologies: ['HTML', 'CSS', 'javaScript'],
	},
	{
		img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
		title: 'Mailchimp Clone',
		des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
		demo: '',
		live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
		gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
		technologies: ['HTML', 'CSS', 'javaScript'],
	},
];
